slug: batteries-and-storage
ord: 2
title:
  lv: Baterijas un to uzglabāšana
  en: Batteries and storage
  ru: Аккумуляторы и хранение
sourceRef: "battery safety | https://www.iata.org/contentassets/05e6d8742b0047259bf3a700bc9d42b9/lithium-battery-guidance-document.pdf; IATA Lithium Battery Guidance | https://www.iata.org/contentassets/05e6d8742b0047259bf3a700bc9d42b9/lithium-battery-guidance-document.pdf; manufacturer manuals | https://www.easa.europa.eu/en/document-library/easy-access-rules/easy-access-rules-unmanned-aircraft-systems-regulations-eu"
