slug: occurrence-reporting
ord: 1
title:
  lv: Atgadījumu ziņošana
  en: Occurrence reporting
  ru: Уведомления о происшествиях
sourceRef: "occurrence reporting in civil aviation | https://www.caa.gov.lv/en/services/reporting-occurrences-civil-aviation; e.caa.gov.lv/incidents | https://e.caa.gov.lv/incidents"
