slug: fatigue-stress
ord: 2
title:
  lv: Nogurums un stress UAS pilotam
  en: Fatigue and stress for the UAS pilot
  ru: Усталость и стресс пилота UAS
sourceRef: "Manual for Fatigue Management; Human Performance | https://www.easa.europa.eu/en/document-library/easy-access-rules/easy-access-rules-unmanned-aircraft-systems-regulations-eu"
