slug: cyber-security
ord: 2
title:
  lv: UAS kiberdrošība
  en: UAS cyber security
  ru: Кибербезопасность UAS
sourceRef: "ENISA Good Practices for UAS cyber security | https://www.enisa.europa.eu/topics/cybersecurity-of-critical-sectors/transport; GNSS spoofing/jamming | https://www.enisa.europa.eu/topics/cybersecurity-of-critical-sectors/transport"
